# Generated by Django 3.0.8 on 2020-07-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techlog', '0002_auto_20200731_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click the link Above to read the blog Post..', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
